join-attempts: 3

force-gamemode:
  # Change player gamemode after login by force.
  enabled: false
  # Available values: SURVIVAL, ADVENTURE, CREATIVE, SPECTATOR.
  gamemode: "SURVIVAL"

timer:
  # Time for a players to log into the server (in seconds).
  register: 30
  # Time of player login under the same ip w/o auth (in minutes).
  session: 30

worlds:
  auth: "world_auth"
  hub-or-survival: "world"