name: WorldAuth
version: '${project.version}'
main: com.myvnc.exo.worldauth.WorldAuth
api-version: 1.17
authors: [ LamberKeep ]
description: A lite Spigot plugin which allows you to add authorization on the server without adding another server or bungeecord.
website: exo.myvnc.com

commands:
  worldauth:
    description: DoubleJump commands
    aliases: wa

  logout:
    description: Log out from account.
    aliases: q

  changepassword:
    description: Change your password.
    aliases: changepass

permissions:
  worldauth.admin:
    description: Allows to use admins commands.
    default: op