name: WorldAuth
version: '${project.version}'
main: com.myvnc.exo.worldauth.WorldAuth
api-version: 1.17
authors: [ LamberKeep ]
description: A lite Spigot plugin which allows you to add authorization on the server without adding another server or bungeecord.
website: exo.myvnc.com

commands:
  register:
    description: Allow to register.
    aliases: reg
  login:
    description: Allows to login.
    aliases: l
  logout:
    description: Allows to logout.
  test:
    description: Removes fly speed (test command).